use datawarehouseanalytics;

-- Database Exploration
select * from information_schema.tables;
select * from information_schema.columns;

select * from information_schema.columns where table_name = 'customers';

describe customers;
describe products;
describe fact_sales;


-- Dimensions Exploration
select distinct country from customers;
select distinct category, subcategory, product_name from products order by 1,2,3;


-- Date Exploration
select min(order_date) as first_order_date, 
max(order_date) as last_order_date,
timestampdiff(year, min(order_date), max(order_date)) as order_range_years from fact_sales;

select min(birthdate) as oldest, max(birthdate) as youngest,
timestampdiff(year, min(birthdate), curdate()) as oldest_person_age,
timestampdiff(year, max(birthdate), curdate()) as youngest_person_age from customers;


-- Measure Exploration
select sum(sales_amount) as total_sales,
sum(quantity) as total_qty,
avg(price) as avg_price,
count(order_number) as total_orders,
count(distinct order_number) as distinct_total_orders,
count(customer_key) as total_orders_place_by_customers,
count(distinct customer_key) as total_distinct_customers_that_placed_orders from fact_sales;

select count(product_key) as total_products from products;
select count(customer_key) as total_customers from customers;

-- Making Report that shows all the metrics of the business
create view measures_report as
select "Total Sales" as Measure_Name, sum(sales_amount) as Mesure_Value from fact_sales union all
select "Total Quantity" as Measure_Name, sum(quantity) as Mesure_Value from fact_sales union all
select "Average Price" as Measure_Name, avg(price) as Mesure_Value from fact_sales union all
select "Total Orders" as Measure_Name, count(order_number) as Mesure_Value from fact_sales union all
select "Distinct Total Orders" as Measure_Name, count(distinct order_number) as Mesure_Value from fact_sales union all
select "Total Orders Place by Customers" as Measure_Name, count(customer_key) as Mesure_Value from fact_sales union all
select "Total Distinct Customers That Placed Orders" as Measure_Name, count(distinct customer_key) as Mesure_Value from fact_sales union all
select "Total Products" as Measure_Name, count(product_key) as Mesure_Value from products union all
select "Total Customers" as Measure_Name, count(customer_key) as Mesure_Value from customers;

select * from measures_report;

-- Magnitude = Comparing measure values by categories which helps to understand importance of different categories.

-- Total Cx by Countries
select country, count(customer_key) as total_customers from customers group by country order by count(customer_key) desc;

-- Total Cx by Gender
select gender, count(customer_key) as total_customers from customers group by gender order by count(customer_key) desc;

-- Total Products by Category
select category, count(product_key) as total_products from products group by category order by total_products desc;

-- Average Cost in Each Category
select category, avg(cost) as average_cost from products group by category order by average_cost desc;

-- Total Revenue Generated for each Category
select p.category, sum(s.sales_amount) as total_revenue from fact_sales s left join products p on s.product_key = p.product_key group by category order by total_revenue desc;

-- Total Revenue Generated by each Customer
select c.customer_key, c.first_name, c.last_name, sum(s.sales_amount) as total_revenue from fact_sales s left join customers c 
on s.customer_key = c.customer_key group by customer_key, first_name, last_name order by total_revenue desc;

-- Distribution of Sold Items Across Countries.
select c.country, sum(s.quantity) as total_items_sold from fact_sales s left join customers c 
on s.customer_key = c.customer_key group by country order by total_items_sold desc;


-- Ranking Top N and Bottom N

-- Which 5 Products generate the hightest revenue?
select p.product_name, sum(sales_amount) as total_sales from fact_sales s left join products p
on s.product_key = p.product_key group by product_name order by total_sales desc limit 5;        
                    -- Using Window Function
select * from (select p.product_name, sum(sales_amount) as total_sales, row_number() over(order by sum(sales_amount) desc) as ranks from fact_sales s left join products p
on s.product_key = p.product_key group by product_name) t where ranks <=5;


-- What are the 5 worst performing products in terms of sales?
select p.product_name, sum(sales_amount) as total_sales from fact_sales s left join products p
on s.product_key = p.product_key group by product_name order by total_sales asc limit 5;

-- Find 3 Customers with the fewest orders placed.
select c.customer_key, c.first_name, c.last_name, count(distinct s.order_number) as total_orders
from fact_sales s left join customers c on s.customer_key = c.customer_key 
group by customer_key, first_name, last_name order by total_orders asc limit 3;